### ISSUE TITLE
Mobile Version - description inside

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/spectrum#26]
[Mobile layout updated.pdf](https://github.com/TehZarathustra/spectrum/files/120836/Mobile.layout.updated.pdf)

**Comment by Artemk23** [comment]
1. About Us - stays the same, except it should be on the separate .html
2. Services:   - BG image should be full page, with black to transparent gradient from lower edge of the image, except for Lutron page)
                    - Contact icons - moved to the bottom right corner of the screen. "Directions" icon is removed, "More Info" - became an "i" icon
                    - If user taps on the image it should perform "before/after" action (except for Lutron - visitor have to click in the switch)
3. Due to removing all  sliders and majority of the images, will be possible to integrate accelerometer or gyroscope feature, just like on the example i showed you. so the visitor will be able to view the BG image in more creative way?

**Comment by TehZarathustra** [comment]
https://github.com/TehZarathustra/spectrum-mobile
