### ISSUE TITLE
Services page: if user taps on the room - hover effect should occur, if user taps on the service title system should open the service's page

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/spectrum#38]

**Comment by TehZarathustra** [comment]
Можешь объяснить, исходя из планшетов, как оно сейчас работает? Полагаю, нам нужно сделать, чтобы не ховерилось по тайтлам, а сразу переходило, а все остально оставить?

**Comment by TehZarathustra** [comment]
https://github.com/TehZarathustra/spectrum/commit/f4a72e2098e96a2e88e7ee7bcebec707005ed1b4
