### ISSUE TITLE
Font-sizes has be be changed ( More Details inside)

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/spectrum#50]
![screen shot 2016-03-20 at 10 39 31 pm](https://cloud.githubusercontent.com/assets/17010253/13925873/4509d8f6-ef47-11e5-941d-5be194c446b1.png)
Main "Event Lighting" title - font-size should be 3.5em

**Comment by Artemk23** [comment]
![screen shot 2016-03-21 at 9 15 35 am](https://cloud.githubusercontent.com/assets/17010253/13925888/55f19b72-ef47-11e5-9922-3bd96aa30c6d.png)
Lutron - Header section:
Text should be aligned with the "More Info" button

**Comment by Artemk23** [comment]
![screen shot 2016-03-21 at 9 17 47 am](https://cloud.githubusercontent.com/assets/17010253/13925914/70a42958-ef47-11e5-8c67-7a6f1dfe95a1.png)
Lutron - Third section ( Shading)
Main title's font-size should be 1.5em

**Comment by Artemk23** [comment]
![screen shot 2016-03-21 at 9 19 46 am](https://cloud.githubusercontent.com/assets/17010253/13925931/7b142f3c-ef47-11e5-8735-240d87aa76a6.png)
- Secondary title's font-size should be smaller than main title's font-szie
- Make secondary title's block wider so it won't go to the second row if less than 30 characters entered

**Comment by Artemk23** [comment]
Font-weight for regular text should be at least 400 (everywhere)

**Comment by Artemk23** [comment]
ABOUT US Page: Main Text for style should be "Raleway"

**Comment by TehZarathustra** [comment]
https://github.com/TehZarathustra/spectrum/commit/3fea97affc148393aede1d47d94dc0fd150e0410
