### ISSUE TITLE
All items at slide-out menu should be written with capital letters

### ISSUE THREAD

**Issue by Artemk23** [TehZarathustra/spectrum#8]

**Comment by TehZarathustra** [comment]
Вообще не очень, когда все большими буквами. Выглядит так себе, тем не менее добавил. Если захочется вернуть обратно, то давай

**Comment by TehZarathustra** [comment]
https://github.com/TehZarathustra/spectrum/commit/9a023e2f589dabf39ec5448c36b77bbf35b419e8
